export type { default as IEntity } from './_Entity'
export type { default as ILogo } from './_Logo'
export type { default as ISection } from './_Section'
export type { default as ISEO } from './_SEO'
export type * from './_StrapiMedia'
export type { default as IClient } from './Client'
export type { default as IHome } from './Home'
export type { default as IProject } from './Project'
export type { default as IService } from './Service'
export type { default as ITestimonial } from './Testimonial'
